version: 2.1

orbs: 
  node: circleci/node@5.0.2
  blns-audit: blns/audit-npm@0.1.3

executors: 
  node: 
    docker: 
      - image: cimg/node:12.18.3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          HUSKY: '0'
          CI: '1'

commands:
  build: 
    description: "Compile Typescript from source"
    steps:
      - run:  
          name: "Compile"
          command: npm run build 
  start:
    description: "Start compiled application"
    steps:
      - run: 
          name: "Start"
          command: npm run start

jobs:
  build-run:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - build
      - start
  audit-notify:
    executor: node
    steps:
      - checkout
      - blns-audit/audit
      - blns-audit/notify

workflows:
  build-test-run:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - build-run
  audit:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - audit-notify
