version: 2.1

orbs: 
  node: circleci/node@5.0.2

executors: 
  node: 
    docker: 
      - image: cimg/node:12.18.3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          HUSKY: '0'
          CI: '1'

commands:
  build: 
    description: "Compile Typescript from source"
    steps:
      - run:  
          name: "Compile"
          command: npm run build 
  run:
    description: "Run compiled application"
    steps:
      - run: 
          name: "Run"
          command: npm run start

jobs:
  build-run:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - build
      - run

workflows:
  build-test-run:
    jobs:
      - build-run
